function createfigure(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6)
%CREATEFIGURE(cdata1, cdata2, cdata3, cdata4, cdata5, cdata6)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata
%  CDATA5:  image cdata
%  CDATA6:  image cdata

%  Auto-generated by MATLAB on 23-Jul-2019 15:34:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0307291666666667 0.566722244160707 0.2515625 0.289631872230266]);
hold(axes1,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create title
title('Hadamard');

axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes1);

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.0333333333333333 0.0921635733403538 0.252604166666667 0.290831176049025]);
hold(axes2,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata2,'Parent',axes2,'CDataMapping','scaled');

% Create title
title('Naive');

axis(axes2,'tight');
% Set the remaining axes properties
set(axes2,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes2);

% Create axes
axes3 = axes('Parent',figure1,...
    'Position',[0.35625 0.565603381451743 0.252604166666667 0.290831176049025]);
hold(axes3,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata3,'Parent',axes3,'CDataMapping','scaled');

% Create title
title('Hadamard - Normalized');

axis(axes3,'tight');
% Set the remaining axes properties
set(axes3,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes3);

% Create axes
axes4 = axes('Parent',figure1,...
    'Position',[0.358333333333333 0.0941014728035922 0.251041666666667 0.289032220320887]);
hold(axes4,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata4,'Parent',axes4,'CDataMapping','scaled');

% Create title
title('Naive - Normalized');

axis(axes4,'tight');
% Set the remaining axes properties
set(axes4,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes4);

% Create axes
axes5 = axes('Parent',figure1,...
    'Position',[0.68608993902439 0.56844075877905 0.250368394308943 0.288257060535592]);
hold(axes5,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata5,'Parent',axes5,'CDataMapping','scaled');

% Create title
title('Hadamard (log)');

axis(axes5,'tight');
% Set the remaining axes properties
set(axes5,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes5);

% Create axes
axes6 = axes('Parent',figure1,...
    'Position',[0.6875 0.0962587571117254 0.248958333333333 0.286633612683369]);
hold(axes6,'on');

% Create image
image([65 65.5 66 66.5 67 67.5 68 68.5 69 69.5 70 70.5 71 71.5 72 72.5 73 73.5 74 74.5 75 75.5 76 76.5 77 77.5 78 78.5 79 79.5 80 80.5 81 81.5 82 82.5 83 83.5 84 84.5 85 85.5 86 86.5 87 87.5 88 88.5 89 89.5 90 90.5 91 91.5 92 92.5 93 93.5 94 94.5 95 95.5 96 96.5 97 97.5 98 98.5 99 99.5 100],...
    [128 127.5 127 126.5 126 125.5 125 124.5 124 123.5 123 122.5 122 121.5 121 120.5 120 119.5 119 118.5 118 117.5 117 116.5 116 115.5 115 114.5 114 113.5 113 112.5 112 111.5 111 110.5 110 109.5 109 108.5 108],...
    cdata6,'Parent',axes6,'CDataMapping','scaled');

% Create title
title('Naive (log)');

axis(axes6,'tight');
% Set the remaining axes properties
set(axes6,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[17.75 10.25 1]);
% Create colorbar
colorbar(axes6);

